version : 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
    commands:
      - echo Installing dependencies
      - composer install --no-dev --optimize-autoloader
  pre_build:
    commands:
      - echo Pre-build stage complete

  build:
    commands:
      - echo Build stage complete

  post_build:
    commands:
      - echo Post-build stage complete
      - echo Deploying to Elastic Beanstalk...
artifacts:
  files:
    - '**/*'

cache:
  paths:
    - vendor/**/* # Cache Composer dependencies

env:
  shell: bash