version : 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
    commands:
      - echo Installing dependencies
      - composer install # Assuming you're using Composer for dependency management
  pre_build:
    commands:
      - echo Running pre-build steps
      - composer run-script pre-build

  build:
    commands:
      - echo Building the application

  post_build:
    commands:
      - echo Running post-build steps
      - composer run-script post-build # if you have scripts defined

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - vendor/**/* # Cache Composer dependencies

env:
  shell: bash